# Generated by Django 4.2.2 on 2023-06-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povrch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturedb',
            name='webpage',
            field=models.URLField(default='www.seznam.cz'),
            preserve_default=False,
        ),
    ]
